author:
  facebook: " https://facebook.com.br/example"
  twitter: " https://x.com.br/example"
  email: " contact@example.com"
  name: "Acme Corporation"
  location: "São Paulo"
  phone: "(999) 999-9999"
  hours: "Mon-Fri: 9:00AM - 6:00PM, ET"
